variable "aws_create" {
  description = "Controls if AWS resources should be performed to in the one-click."
  type        = bool
  default     = true
}

variable "aws_availability_zones" {
  description = "Subnet and application AWS Availability Zones."
  type        = list(string)
  default     = ["a", "b", "c"]
}

variable "aws_vpc_name" {
  description = "Name for the VPC."
  type        = string
  default     = "PredMaintAWSMongoDB"
}

variable "aws_allowed_ips" {
  description = "List of allowed CIDR blocks for ALB and default security group ingress. Defaults to MongoDB office and partner IP ranges."
  type        = list(string)
  default = [
    "4.35.206.216/29",
    "97.77.203.56/29",
    "14.195.102.136/29",
    "61.246.212.64/29",
    "212.56.8.40/29",
    "83.221.128.34/32",
    "77.107.233.160/29",
    "89.101.148.232/29",
    "182.76.117.48/29",
    "14.98.65.56/29",
    "81.101.80.80/28",
    "74.113.166.152/29",
    "162.213.133.99/32",
    "207.251.78.32/29",
    "206.252.195.126/32",
    "204.153.194.96/29",
    "50.175.168.144/29",
    "213.41.116.16/29",
    "12.196.188.168/29",
    "50.175.175.240/29",
    "14.200.46.128/29",
    "123.103.203.216/29",
    "124.254.96.131/32",
    "104.30.164.0/28",
    "44.220.233.194/32",
    "34.200.14.156/32",
    "63.32.217.76/32",
    "3.250.248.128/32",
    "13.201.114.222/32",
    "18.228.127.246/32",
    "3.77.23.139/32",
    "3.86.32.96/32",
  ]
}

variable "aws_cluster_name" {
  description = "Name for the ECS cluster."
  type        = string
  default     = "Pred-Maint-AWS-MongoDB"
}

variable "aws_container_name" {
  description = "Name for the ECS container."
  type        = string
  default     = "predictive-maintenance"
}

variable "aws_image" {
  description = "Full image (repository/prefix/name:tag) reference."
  type        = string
  default     = ""
}

variable "aws_app_name" {
  description = "Name used for app resources created on the ECS cluster and other services."
  type        = string
  default     = "pred-maint-aws-mongodb"
}

variable "aws_app_envs" {
  description = "Key-value pairs to be included in the environment variables used by the app."
  type        = map(string)
  default = {
    "PORT" : "3001"
  }
}

variable "app_indexing" {
  description = "Controls if indexing should be performed to MongoBD cluster."
  type        = bool
  default     = true
}

variable "app_generate_models" {
  description = "Controls if models should be generated by the application."
  type        = bool
  default     = false
}

variable "app_simulation" {
  description = "Controls if sample predictions using historical data should be perfomed by the app."
  type        = bool
  default     = true
}

variable "app_use_public_ecr" {
  description = "Controls if app should use the public image of the application."
  type        = bool
  default     = true
}

variable "atlas_create" {
  description = "Controls if Mongo Atlas cluster should be created."
  type        = bool
  default     = true
}

variable "atlas_project_name" {
  description = "Name of the MongoDB Atlas project"
  type        = string
  default     = "Pred-Maint-AWS-MongoDB"
}

variable "atlas_cluster_name" {
  description = "Name of the MongoDB Atlas cluster"
  type        = string
  default     = "predictive-maintenance"
}


variable "atlas_cluster_instance_size_name" {
  description = "Atlas cluster instance size (e.g., M0, M10)"
  type        = string
  default     = "M10"
}

variable "atlas_cluster_region_name" {
  description = "AWS region for the cluster"
  type        = string
  default     = "US_EAST_1"
}

variable "atlas_allowed_ips" {
  description = "List of public IPs allowed to connect to the Atlas cluster. Supports IPs and CIDR blocks. Defaults to MongoDB office and partner IP ranges."
  type        = list(string)
  default = [
    "4.35.206.216/29",
    "97.77.203.56/29",
    "14.195.102.136/29",
    "61.246.212.64/29",
    "212.56.8.40/29",
    "83.221.128.34/32",
    "77.107.233.160/29",
    "89.101.148.232/29",
    "182.76.117.48/29",
    "14.98.65.56/29",
    "81.101.80.80/28",
    "74.113.166.152/29",
    "162.213.133.99/32",
    "207.251.78.32/29",
    "206.252.195.126/32",
    "204.153.194.96/29",
    "50.175.168.144/29",
    "213.41.116.16/29",
    "12.196.188.168/29",
    "50.175.175.240/29",
    "14.200.46.128/29",
    "123.103.203.216/29",
    "124.254.96.131/32",
    "104.30.164.0/28",
    "44.220.233.194/32",
    "34.200.14.156/32",
    "63.32.217.76/32",
    "3.250.248.128/32",
    "13.201.114.222/32",
    "18.228.127.246/32",
    "3.77.23.139/32",
    "3.86.32.96/32",
  ]
}

variable "atlas_org_id" {
  description = "The ID of the MongoDB Atlas organization"
  type        = string
  default     = ""
}

variable "atlas_public_key" {
  description = "Public key for MongoDB Atlas API"
  type        = string
  sensitive   = true
  default     = ""
}

variable "atlas_private_key" {
  description = "Private key for MongoDB Atlas API"
  type        = string
  sensitive   = true
  default     = ""
}

variable "atlas_password" {
  description = "Password for admin user."
  type        = string
  sensitive   = true
  default     = ""
}

variable "mongodb_uri" {
  description = "External MongoDB connection URI. Used when atlas_create is false."
  type        = string
  sensitive   = true
  default     = ""
}

variable "voyage_api_key" {
  description = "API key for Voyage AI embedding and reranking services."
  type        = string
  sensitive   = true
  default     = ""
}

variable "acm_certificate_arn" {
  description = "ARN of ACM certificate for HTTPS on the ALB. Leave empty for HTTP only."
  type        = string
  default     = ""
}

variable "alert_email" {
  description = "Email address for critical alert notifications via SNS."
  type        = string
  default     = ""
}